#!/bin/bash

set -euo pipefail

EXTRA_ARGS=()

# Additional args for enabling Wayland
if [[ "${XDG_SESSION_TYPE}" == "wayland" ]]; then
    EXTRA_ARGS+=(
        "--ozone-platform=wayland"
    )
fi

export TMPDIR="${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}"
exec zypak-wrapper /app/bin/jitsi-meet/jitsi-meet "${EXTRA_ARGS[@]}" "$@"
